import { NextRequest, NextResponse } from 'next/server';

interface StadiumData {
  username: string;
  schoolName: string;
  mascot: string;
  colors: {
    primary: string;
    secondary: string;
  };
  sports: string[];
  goals: string[];
  bio: string;
}

interface CreatedStadium extends StadiumData {
  id: string;
  createdAt: string;
  heroCardGenerated: boolean;
  aiTrainerAssigned: boolean;
}

// In-memory storage for stadiums (in production, use a database)
const stadiums: CreatedStadium[] = [];

export async function POST(request: NextRequest) {
  try {
    const data: StadiumData = await request.json();
    
    // Validate required fields
    if (!data.username || !data.schoolName || !data.mascot || !data.bio) {
      return NextResponse.json(
        { error: 'Username, school name, mascot, and bio are required' },
        { status: 400 }
      );
    }

    // Check if username already exists
    const existingStadium = stadiums.find(stadium => stadium.username === data.username);
    if (existingStadium) {
      return NextResponse.json(
        { error: 'Username already taken' },
        { status: 409 }
      );
    }

    // Generate unique stadium ID
    const stadiumId = `stadium_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

    // Create the stadium
    const newStadium: CreatedStadium = {
      ...data,
      id: stadiumId,
      createdAt: new Date().toISOString(),
      heroCardGenerated: false, // Will be generated by AI
      aiTrainerAssigned: false // Will be assigned based on mascot
    };

    stadiums.push(newStadium);

    // Simulate AI processing
    setTimeout(async () => {
      // Here we would trigger:
      // 1. HeroCard generation via DesignMaster bot
      // 2. AI Trainer assignment based on school mascot
      // 3. School theming application
      // 4. Welcome message from Gage Coleman
      
      newStadium.heroCardGenerated = true;
      newStadium.aiTrainerAssigned = true;
      
      console.log(`Stadium ${data.username} fully initialized with AI features`);
    }, 2000);

    // Log the creation
    console.log('New stadium created:', {
      username: data.username,
      school: data.schoolName,
      mascot: data.mascot,
      sports: data.sports,
      goals: data.goals,
      stadiumId,
      totalStadiums: stadiums.length
    });

    return NextResponse.json(
      { 
        success: true, 
        message: 'Stadium created successfully',
        stadium: {
          id: stadiumId,
          username: data.username,
          url: `/stadium/${data.username}`
        }
      },
      { status: 201 }
    );

  } catch (error) {
    console.error('Stadium creation error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

// GET endpoint to retrieve stadium by username
export async function GET(request: NextRequest) {
  const url = new URL(request.url);
  const username = url.searchParams.get('username');

  if (!username) {
    return NextResponse.json(
      { error: 'Username parameter required' },
      { status: 400 }
    );
  }

  const stadium = stadiums.find(s => s.username === username);
  
  if (!stadium) {
    return NextResponse.json(
      { error: 'Stadium not found' },
      { status: 404 }
    );
  }

  return NextResponse.json({
    stadium: {
      ...stadium,
      // Don't expose internal IDs in public API
      id: undefined
    }
  });
}